FROM pangeo/base-notebook:latest AS release

# Base Stage ****************************************************************
USER root
WORKDIR /

RUN set -ve

RUN apt update
RUN apt install --no-install-recommends -y \
        software-properties-common \
        git && \
    apt-get install -y gpg-agent && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt update && \
    apt upgrade -y

RUN apt install --no-install-recommends --fix-missing -y \
    ### PyGMTSAR
    csh \
    autoconf \
    make \ 
    libtiff5-dev \ 
    liblapack-dev \
    libgmt-dev \
    gmt-dcw \
    gmt-gshhg \
    gmt \
    gcc \
    gfortran \
    --

RUN python3 -m pip install \
        jupyterlab-jupyterbook-navigation==1.0.0 \
        ### For pyGMTSAR
        pygmtsar &&\
    cd / &&\
        mkdir -p /tmp/build/GMTSAR /usr/local/GMTSAR &&\
        git clone --branch master https://github.com/gmtsar/gmtsar /tmp/build/GMTSAR/ &&\
        cd /tmp/build/GMTSAR &&\
        autoconf &&\
        ./configure --with-orbits-dir=/tmp CFLAGS='-z muldefs' LDFLAGS='-z muldefs' &&\
        make &&\
        make install &&\
        mv -v /tmp/build/GMTSAR/bin /usr/local/GMTSAR/bin &&\
        rm -rf /tmp/build &&\
    cd /

RUN wget https://raw.githubusercontent.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/main/environment.yaml -P /etc/env/ && \
    mamba env create -f /etc/env/environment.yaml && \
    /srv/conda/envs/opensarlab_mintpy_recipe_book/bin/python -m ipykernel install --prefix /srv/conda/envs/opensarlab_mintpy_recipe_book --name opensarlab_mintpy_recipe_book && \
    mamba clean --yes --all && \
    chmod -R 755 /srv/conda/envs && \
    chown -R jovyan:users /srv/conda/envs

### GMTSAR
ENV PATH=/usr/local/GMTSAR/bin:$PATH

WORKDIR /home/jovyan
USER jovyan
